# Generated by Django 5.1.2 on 2024-11-28 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ligameet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(default='', max_length=30)),
                ('LAST_NAME', models.CharField(default='', max_length=30)),
                ('MIDDLE_NAME', models.CharField(blank=True, max_length=30, null=True)),
                ('DATE_OF_BIRTH', models.DateField(blank=True, null=True)),
                ('GENDER', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='-', max_length=1)),
                ('ADDRESS', models.CharField(blank=True, max_length=255, null=True)),
                ('HEIGHT', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('WEIGHT', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PHONE', models.CharField(blank=True, max_length=15, null=True)),
                ('INV_CODE', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('role', models.CharField(blank=True, choices=[('Player', 'Player'), ('Coach', 'Coach'), ('Scout', 'Scout'), ('Event Organizer', 'Event Organizer')], max_length=50, null=True)),
                ('image', models.ImageField(default='user_default.png', upload_to='profile_pics')),
                ('first_login', models.BooleanField(default=True)),
                ('is_scout', models.BooleanField(default=False)),
                ('volleyball_position_played', models.CharField(blank=True, max_length=50, null=True)),
                ('volleyball_jersey_number', models.IntegerField(blank=True, null=True)),
                ('volleyball_previous_teams', models.TextField(blank=True, null=True)),
                ('basketball_position_played', models.CharField(blank=True, max_length=50, null=True)),
                ('basketball_jersey_number', models.IntegerField(blank=True, null=True)),
                ('basketball_previous_teams', models.TextField(blank=True, null=True)),
                ('preferred_league_level', models.CharField(blank=True, max_length=50, null=True)),
                ('basketball_playing_style', models.CharField(blank=True, max_length=50, null=True)),
                ('vertical_leap', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wingspan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('basketball_achievements', models.TextField(blank=True, null=True)),
                ('spike_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('block_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('serving_style', models.CharField(blank=True, max_length=50, null=True)),
                ('volleyball_achievements', models.TextField(blank=True, null=True)),
                ('preferred_hand', models.CharField(blank=True, max_length=15, null=True)),
                ('medical_info', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_coaches', models.TextField(blank=True, null=True)),
                ('sports', models.ManyToManyField(blank=True, to='ligameet.sportprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
