# Generated by Django 5.0.1 on 2024-11-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='basketball_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='volleyball_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
