# Generated by Django 5.1.2 on 2025-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/user_default.png', upload_to='profile_pics/'),
        ),
    ]
