# Generated by Django 5.0.1 on 2024-11-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_basketball_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='basketball_position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='volleyball_position',
        ),
    ]
