# Generated by Django 5.0.1 on 2024-11-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_basketball_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='basketball_achievements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='basketball_playing_style',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='block_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position_played',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='serving_style',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='spike_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vertical_leap',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='volleyball_achievements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wingspan',
        ),
    ]
