# Generated by Django 5.0.7 on 2024-08-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_contact_info_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
