# Generated by Django 5.0.1 on 2024-10-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='basketball_achievements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='basketball_playing_style',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='block_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jersey_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='medical_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position_played',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_coaches',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_hand',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_league_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='previous_teams',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='serving_style',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='spike_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sports',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vertical_leap',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='volleyball_achievements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wingspan',
        ),
    ]
