# Generated by Django 5.0.1 on 2024-11-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_basketball_achievements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='jersey_number',
            new_name='bjersey_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='position_played',
            new_name='bposition_played',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='preferred_hand',
            new_name='bpreferred_hand',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='previous_teams',
            new_name='bprevious_teams',
        ),
        migrations.AddField(
            model_name='profile',
            name='vjersey_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vposition_played',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vpreferred_hand',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vprevious_teams',
            field=models.TextField(blank=True, null=True),
        ),
    ]
