# Generated by Django 5.1.2 on 2025-09-30 09:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='user_default.png', max_length=255, verbose_name='image'),
        ),
    ]
