# Generated by Django 5.0.1 on 2024-11-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_jersey_number_profile_bjersey_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bpreferred_hand',
            new_name='preferred_hand',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vpreferred_hand',
        ),
    ]
