# Generated by Django 5.0.7 on 2024-10-14 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0008_alter_event_event_image'),
        ('users', '0006_profile_availability_profile_basketball_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ligameet.sport'),
        ),
    ]
