# Generated by Django 5.0.1 on 2024-11-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0018_remove_event_registration_deadline_and_more'),
        ('users', '0007_rename_bpreferred_hand_profile_preferred_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sport',
            field=models.ManyToManyField(blank=True, to='ligameet.sport'),
        ),
    ]
