# Generated by Django 5.0.7 on 2024-10-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sport',
        ),
    ]
