# Generated by Django 5.0.7 on 2024-09-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_address_profile_date_of_birth_profile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='ADDRESS',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='DATE_OF_BIRTH',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='FIRST_NAME',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='GENDER',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='height',
            new_name='HEIGHT',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='inv_code',
            new_name='INV_CODE',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_athlete',
            new_name='IS_ATHLETE',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_coach',
            new_name='IS_COACH',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_event_org',
            new_name='IS_EVENT_ORG',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_scout',
            new_name='IS_SCOUT',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='LAST_NAME',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='middle_name',
            new_name='MIDDLE_NAME',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='PHONE',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='type',
            new_name='TYPE',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='USER',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='weight',
            new_name='WEIGHT',
        ),
    ]
