# Generated by Django 5.0.7 on 2024-10-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0010_rename_participant_sportprofile'),
        ('users', '0008_remove_profile_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='SportProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ligameet.sportprofile'),
        ),
    ]
