# Generated by Django 5.0.1 on 2024-11-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sport',
        ),
    ]
