# Generated by Django 5.0.7 on 2024-09-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_address_profile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='USER',
            new_name='user',
        ),
    ]
