# Generated by Django 5.0.1 on 2024-10-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0011_event_is_sponsored_event_number_of_teams_and_more'),
        ('users', '0009_profile_sportprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='SportProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='sports',
            field=models.ManyToManyField(blank=True, to='ligameet.sportprofile'),
        ),
    ]
