# Generated by Django 5.1.2 on 2024-11-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_scout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Player', 'Player'), ('Coach', 'Coach'), ('Event Organizer', 'Event Organizer')], max_length=50, null=True),
        ),
    ]
