# Generated by Django 5.0.7 on 2024-09-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_user_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='EMAIL',
        ),
    ]
