# Generated by Django 5.0.1 on 2024-11-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_is_scout_alter_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bjersey_number',
            new_name='basketball_jersey_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='bposition_played',
            new_name='basketball_position_played',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='bprevious_teams',
            new_name='basketball_previous_teams',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='vjersey_number',
            new_name='volleyball_jersey_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='vposition_played',
            new_name='volleyball_position_played',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='vprevious_teams',
            new_name='volleyball_previous_teams',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Player', 'Player'), ('Coach', 'Coach'), ('Scout', 'Scout'), ('Event Organizer', 'Event Organizer')], max_length=50, null=True),
        ),
    ]
