services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn cap2.asgi:application -k uvicorn.workers.UvicornWorker'