# Generated by Django 5.1.2 on 2024-10-22 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_alter_chatgroup_group_name'),
        ('ligameet', '0015_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_groups', to='ligameet.team'),
        ),
    ]
