# Generated by Django 5.0.1 on 2024-09-28 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('profile_update', 'Profile Update'), ('join_team', 'Join Team'), ('leave_team', 'Leave Team'), ('create_event', 'Create Event'), ('register_fee_payment', 'Register Fee Payment'), ('subscription_payment', 'Subscription Payment'), ('team_win', 'Team Win'), ('team_loss', 'Team Loss')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
