# Generated by Django 5.0.7 on 2024-08-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='sports_icon/'),
        ),
    ]
