# Generated by Django 5.1.2 on 2024-12-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='match',
            name='bracket_type',
            field=models.CharField(choices=[('WINNER', 'Winner Bracket'), ('LOSER', 'Loser Bracket')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_number',
        ),
        migrations.RemoveField(
            model_name='match',
            name='sport_details',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
    ]
