# Generated by Django 5.1.2 on 2024-10-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EVENT_IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
