# Generated by Django 5.1.2 on 2024-11-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportrequirement',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_requirements', to='ligameet.event'),
        ),
        migrations.AlterField(
            model_name='sportrequirement',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='ligameet.sport'),
        ),
        migrations.AlterField(
            model_name='teamcategory',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_categories', to='ligameet.event'),
        ),
        migrations.AlterField(
            model_name='teamcategory',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ligameet.sport'),
        ),
    ]
