# Generated by Django 5.0.7 on 2024-10-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='SPORT_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ligameet.sport'),
        ),
    ]
