# Generated by Django 5.1.2 on 2025-10-02 06:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EVENT_IMAGE',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='IMAGE',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='TEAM_LOGO',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
