# Generated by Django 5.0.1 on 2024-09-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0002_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
