# Generated by Django 5.0.1 on 2024-11-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0002_alter_sportrequirement_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportprofile',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
