# Generated by Django 5.1.2 on 2024-12-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0002_bracketdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-schedule']},
        ),
        migrations.RenameField(
            model_name='match',
            old_name='MATCH_DATE',
            new_name='schedule',
        ),
        migrations.RemoveField(
            model_name='match',
            name='MATCH_CATEGORY',
        ),
        migrations.RemoveField(
            model_name='match',
            name='MATCH_SCORE',
        ),
        migrations.RemoveField(
            model_name='match',
            name='MATCH_STATUS',
        ),
        migrations.RemoveField(
            model_name='match',
            name='MATCH_TYPE',
        ),
        migrations.RemoveField(
            model_name='match',
            name='TEAM_ID',
        ),
        migrations.AddField(
            model_name='match',
            name='bracket',
            field=models.CharField(choices=[('Upper Bracket', 'Upper Bracket'), ('Lower Bracket', 'Lower Bracket')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.CharField(choices=[('Round 1', 'Round 1'), ('Quarter-finals', 'Quarter-finals'), ('Semi-finals', 'Semi-finals'), ('Final', 'Final')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_team_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_team_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_a_matches', to='ligameet.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_b_matches', to='ligameet.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='ligameet.team'),
        ),
        migrations.DeleteModel(
            name='MatchDetails',
        ),
    ]
