# Generated by Django 5.0.1 on 2024-10-31 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0003_notification_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='extra_data',
        ),
    ]
