# Generated by Django 5.0.1 on 2024-11-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0003_sportprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportprofile',
            name='position',
        ),
    ]
