# Generated by Django 5.1.2 on 2024-12-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0003_bracketdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketdata',
            name='sport_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='ligameet.sportdetails'),
        ),
        migrations.AddField(
            model_name='bracketdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
