# Generated by Django 5.1.2 on 2024-12-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0003_alter_match_options_rename_match_date_match_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.CharField(choices=[('First Round', 'First Round'), ('Quarter-finals', 'Quarter-finals'), ('Semi-finals', 'Semi-finals'), ('Finals', 'Finals')], max_length=50, null=True),
        ),
    ]
