# Generated by Django 5.0.7 on 2024-10-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0003_rename_timestamp_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EVENT_IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_STATUS',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('finished', 'finished'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10),
        ),
    ]
