# Generated by Django 5.0.1 on 2024-10-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0004_team_pending_players_team_players_joinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='PENDING_PLAYERS',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PLAYERS',
        ),
        migrations.DeleteModel(
            name='JoinRequest',
        ),
    ]
