# Generated by Django 5.0.1 on 2024-11-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0004_remove_sportprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportprofile',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
