# Generated by Django 5.1.2 on 2024-12-11 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0004_alter_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sport_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ligameet.sportdetails'),
        ),
    ]
