# Generated by Django 5.0.7 on 2024-09-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0005_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
