# Generated by Django 5.0.1 on 2024-11-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0005_sportprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportprofile',
            name='position',
        ),
        migrations.AddField(
            model_name='sportprofile',
            name='basketball_achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportprofile',
            name='basketball_playing_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sportprofile',
            name='block_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sportprofile',
            name='position_played',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sportprofile',
            name='serving_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sportprofile',
            name='spike_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sportprofile',
            name='vertical_leap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sportprofile',
            name='volleyball_achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportprofile',
            name='wingspan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
