# Generated by Django 5.1.2 on 2024-12-12 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0005_match_sport_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='volleyballstats',
            old_name='VB_STATS_ASSIST',
            new_name='assists',
        ),
        migrations.RenameField(
            model_name='volleyballstats',
            old_name='VB_STATS_BLOCK',
            new_name='attack_errors',
        ),
        migrations.RenameField(
            model_name='volleyballstats',
            old_name='VB_STATS_ERROR',
            new_name='blocks',
        ),
        migrations.RenameField(
            model_name='volleyballstats',
            old_name='VB_STATS_PT_COUNT',
            new_name='digs',
        ),
        migrations.RenameField(
            model_name='volleyballstats',
            old_name='VB_STATS_SET',
            new_name='kills',
        ),
        migrations.RemoveField(
            model_name='volleyballstats',
            name='MATCH_ID',
        ),
        migrations.RemoveField(
            model_name='volleyballstats',
            name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='volleyballstats',
            name='USER_MATCH_ID',
        ),
        migrations.RemoveField(
            model_name='volleyballstats',
            name='VB_STATS_IS_MVP',
        ),
        migrations.AddField(
            model_name='volleyballstats',
            name='reception_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volleyballstats',
            name='service_aces',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='ligameet.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='ligameet.sport')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='ligameet.team')),
            ],
        ),
        migrations.CreateModel(
            name='BasketballStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('three_pointers_made', models.IntegerField(default=0)),
                ('free_throws_made', models.IntegerField(default=0)),
                ('player_stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basketball_stats', to='ligameet.playerstats')),
            ],
        ),
        migrations.AddField(
            model_name='volleyballstats',
            name='player_stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volleyball_stats', to='ligameet.playerstats'),
        ),
    ]
