# Generated by Django 5.0.7 on 2024-10-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0006_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EVENT_IMAGE',
            field=models.ImageField(default='user_default.png', upload_to='event_images/'),
        ),
    ]
