# Generated by Django 5.0.1 on 2024-10-31 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0006_remove_notification_is_poke_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='can_poke_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='scout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scout_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
