# Generated by Django 5.0.1 on 2024-11-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0006_remove_sportprofile_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportprofile',
            name='basketball_achievements',
        ),
        migrations.RemoveField(
            model_name='sportprofile',
            name='basketball_playing_style',
        ),
        migrations.RemoveField(
            model_name='sportprofile',
            name='block_height',
        ),
        migrations.RemoveField(
            model_name='sportprofile',
            name='position_played',
        ),
        migrations.RemoveField(
            model_name='sportprofile',
            name='serving_style',
        ),
        migrations.RemoveField(
            model_name='sportprofile',
            name='spike_height',
        ),
        migrations.RemoveField(
            model_name='sportprofile',
            name='vertical_leap',
        ),
        migrations.RemoveField(
            model_name='sportprofile',
            name='volleyball_achievements',
        ),
        migrations.RemoveField(
            model_name='sportprofile',
            name='wingspan',
        ),
    ]
