# Generated by Django 5.1.2 on 2024-11-08 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0007_remove_sportprofile_basketball_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportrequirement',
            name='allowed_categories',
        ),
        migrations.AddField(
            model_name='sportrequirement',
            name='allowed_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ligameet.teamcategory'),
        ),
    ]
