# Generated by Django 5.0.1 on 2024-10-31 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0007_notification_can_poke_back_notification_scout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='can_poke_back',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='scout',
        ),
    ]
