# Generated by Django 5.1.2 on 2024-11-08 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0008_remove_sportrequirement_allowed_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportrequirement',
            name='entrance_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Entrance fee should be greater than or equal to 0.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
