# Generated by Django 5.1.2 on 2024-12-13 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0008_alter_playerstats_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together={('player', 'match', 'team')},
        ),
    ]
