# Generated by Django 5.0.7 on 2024-10-14 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0009_participant_participant_unique_user_sport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='SportProfile',
        ),
    ]
