# Generated by Django 5.0.1 on 2024-11-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0009_sportrequirement_entrance_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(related_name='events', through='ligameet.TeamEvent', to='ligameet.team'),
        ),
    ]
