# Generated by Django 5.1.2 on 2024-12-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0009_alter_playerstats_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='volleyballstats',
            name='blocks_score',
            field=models.IntegerField(default=0),
        ),
    ]
