# Generated by Django 5.1.2 on 2024-11-04 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0009_notification_sender_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='SPORT_CATEGORY',
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ligameet.sport')),
            ],
        ),
        migrations.CreateModel(
            name='SportRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_teams', models.PositiveIntegerField(default=0)),
                ('players_per_team', models.PositiveIntegerField(default=0)),
                ('sport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='ligameet.sport')),
                ('allowed_categories', models.ManyToManyField(to='ligameet.teamcategory')),
            ],
        ),
    ]
