# Generated by Django 5.1.2 on 2024-11-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0010_event_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='IS_POSTED',
            field=models.BooleanField(default=False),
        ),
    ]
