# Generated by Django 5.0.1 on 2024-11-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0010_remove_sport_sport_category_teamcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='TEAM_DESCRIPTION',
            field=models.TextField(blank=True, null=True),
        ),
    ]
