# Generated by Django 5.0.7 on 2024-10-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0010_rename_participant_sportprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='IS_SPONSORED',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='NUMBER_OF_TEAMS',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='PAYMENT_FEE',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='PLAYERS_PER_TEAM',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
