# Generated by Django 5.1.2 on 2024-12-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0010_volleyballstats_blocks_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_team_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team_b',
            field=models.IntegerField(default=0),
        ),
    ]
