# Generated by Django 5.1.2 on 2024-11-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0011_team_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcategory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
