# Generated by Django 5.1.2 on 2024-11-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0011_event_is_posted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportRequirement',
            new_name='SportDetails',
        ),
    ]
