# Generated by Django 5.1.2 on 2024-12-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0012_alter_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportdetails',
            name='elimination_type',
            field=models.CharField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.CharField(choices=[('First Round', 'First Round'), ('Quarter-finals', 'Quarter-finals'), ('Semi-finals', 'Semi-finals'), ('Finals', 'Finals'), ('Grand finals', 'Grand finals')], max_length=50, null=True),
        ),
    ]
