# Generated by Django 5.0.1 on 2024-10-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0012_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
