# Generated by Django 5.1.2 on 2024-11-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0012_alter_teamcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportrequirement',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_requirements', to='ligameet.event'),
        ),
    ]
