# Generated by Django 5.1.2 on 2024-11-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0013_sportdetails_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportdetails',
            name='team',
        ),
        migrations.AddField(
            model_name='sportdetails',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='sport_details', to='ligameet.team'),
        ),
    ]
