# Generated by Django 5.1.2 on 2024-11-05 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0013_sportrequirement_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportrequirement',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_requirements', to='ligameet.event'),
        ),
        migrations.AlterField(
            model_name='sportrequirement',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='ligameet.sport'),
        ),
    ]
