# Generated by Django 5.0.7 on 2024-09-09 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0013_usermatch_volleyballstats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAYMENT_AMOUNT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PAYMENT_DATE', models.DateTimeField(default=django.utils.timezone.now)),
                ('SUBSCRIPTION_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ligameet.subscription')),
                ('TEAM_REGISTRATION_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ligameet.teamregistrationfee')),
                ('WALLET_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligameet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRANSACTION_DATE', models.DateTimeField(default=django.utils.timezone.now)),
                ('TRANSACTION_AMOUNT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PAYMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligameet.payment')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistrationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IS_PAID', models.BooleanField(default=False)),
                ('USER_MATCH_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligameet.usermatch')),
            ],
        ),
    ]
