# Generated by Django 5.1.2 on 2024-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0014_remove_event_sport_id_event_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EVENT_IMAGE',
            field=models.ImageField(blank=True, default='event_default.png', null=True, upload_to='event_images/'),
        ),
    ]
