# Generated by Django 5.1.2 on 2024-11-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0014_alter_sportrequirement_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='NUMBER_OF_TEAMS',
        ),
        migrations.RemoveField(
            model_name='event',
            name='PLAYERS_PER_TEAM',
        ),
    ]
