# Generated by Django 5.0.1 on 2024-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0015_alter_event_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamparticipant',
            name='IS_CAPTAIN',
        ),
        migrations.AddField(
            model_name='teamparticipant',
            name='role',
            field=models.CharField(choices=[('Captain', 'Captain'), ('Starter', 'Starter'), ('Bench', 'Bench')], default='Bench', max_length=20),
        ),
    ]
