# Generated by Django 5.1.2 on 2024-11-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0015_alter_event_event_status_playerrecruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='REGISTRATION_DEADLINE',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
