# Generated by Django 5.0.1 on 2024-10-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0016_remove_teamparticipant_is_captain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamparticipant',
            name='role',
        ),
        migrations.AddField(
            model_name='teamparticipant',
            name='IS_CAPTAIN',
            field=models.BooleanField(default=False),
        ),
    ]
