# Generated by Django 5.1.2 on 2024-11-19 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0017_remove_sportdetails_allowed_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='REGISTRATION_DEADLINE',
        ),
        migrations.RemoveField(
            model_name='sportdetails',
            name='team_category',
        ),
        migrations.AddField(
            model_name='sportdetails',
            name='allowed_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ligameet.teamcategory'),
        ),
        migrations.AddField(
            model_name='sportdetails',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_requirements', to='ligameet.event'),
        ),
        migrations.AddField(
            model_name='sportdetails',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='ligameet.sport'),
        ),
    ]
