# Generated by Django 5.1.2 on 2024-11-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0019_remove_sportdetails_allowed_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='REGISTRATION_DEADLINE',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
