# Generated by Django 5.1.2 on 2024-11-20 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0022_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportCategory',
            new_name='TeamCategory',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_team_event_registration',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_user_event_registration',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='sport_category',
            new_name='team_category',
        ),
        migrations.RenameField(
            model_name='sportdetails',
            old_name='sport_category',
            new_name='team_category',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('team', 'event', 'team_category'), name='unique_team_event_registration'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('user', 'event', 'team_category'), name='unique_user_event_registration'),
        ),
    ]
