# Generated by Django 5.0.1 on 2024-11-21 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0024_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='TEAM_ID',
        ),
        migrations.AddField(
            model_name='match',
            name='TEAM1_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='ligameet.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='TEAM2_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='ligameet.team'),
        ),
    ]
