# Generated by Django 5.0.1 on 2024-11-21 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0025_remove_match_team_id_match_team1_id_match_team2_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ligameet.event'),
        ),
    ]
