# Generated by Django 5.0.1 on 2024-11-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0027_remove_match_team1_id_remove_match_team2_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='TEAM_ID',
        ),
    ]
